CPP = c++

FLAGS = -Wall -Wextra -Werror -std=c++98

TARGET = megaphone

$(TARGET):
	$(CPP) $(FLAGS) megaphone.cpp -o $(TARGET) 

clean:
	$(RM) $(RM_OPTION) $(TARGET)

fclean: clean

re: fclean $(TARGET)
